build:
	gcc -Wall -ggdb -D SRPT_PACKAGED -o ./pack ./pack.c ../renderer.c ../../serpent/serpent.c ../../sdom.c ../../utils.c ../../include/glad/glad.c ../shaders.o ./pack.o  -lglfw -lwayland-client -lm -I../../include/ -I../../serpent
