name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev xorg-dev pkg-config
    - name: environment
      run: |
        export PKG_CONFIG_PATH=/usr/lib/pkgconfig/:$PKG_CONFIG_PATH
    - name: make
      run: make -C src/ setup build-x
