name: Create release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build ig
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev xorg-dev libwayland-client0 pkg-config
      - name: environment
        run: |
          export PKG_CONFIG_PATH=/usr/lib/pkgconfig/:$PKG_CONFIG_PATH
      - name: make
        run: make -C src/ setup build build-x #build-windows
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes \
              'bin/srpt#Linux ELF x86-64 Wayland'\\
              'bin/srptx#Linux ELF x86-64 X11'\\
              #'bin/windows.exe#Windows'\\
